admin_proposition:
    resource: "@AdminPropositionBundle/Resources/config/routing.yml"
    prefix:   /admin/proposition

admin_contact:
    resource: "@AdminContactBundle/Resources/config/routing.yml"
    prefix:   /admin/contact

admin_product:
    resource: "@AdminProductBundle/Resources/config/routing.yml"
    prefix:   /admin/product

admin_loggin:
    resource: "@AdminLogginBundle/Resources/config/routing.yml"
    prefix:   /admin/loggin

admin_partner:
    resource: "@AdminPartnerBundle/Resources/config/routing.yml"
    prefix:   /admin/partner

admin_news:
    resource: "@AdminNewsBundle/Resources/config/routing.yml"
    prefix:   /admin/news

admin_daily_menu:
    resource: "@AdminDailyMenuBundle/Resources/config/routing.yml"
    prefix:   /admin/dailymenu

admin_category:
    resource: "@AdminCategoryBundle/Resources/config/routing.yml"
    prefix:   /admin/category
   
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    
