security:

    providers:
        in_memory:
            memory: 
                users:
                    restoadm:
                        password: "%admin_password%"
                        roles: 'ROLE_ADMIN'
    
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 1 year
                path: /
        
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
