admin_category_home:
    path: /
    defaults: { _controller: AdminCategoryBundle:List:index}
    
admin_category_detail:
    path: /detail/{id}
    defaults: { _controller: AdminCategoryBundle:List:detail }
    requirements:
        id: \d+

admin_category_add:
    path: /add
    defaults: { _controller: AdminCategoryBundle:List:add }
    
admin_category_edit:
    path: /edit/{id}
    defaults: { _controller: AdminCategoryBundle:List:edit }
    requirements:
         id: \d+
         
admin_category_delete:
    path: /delete/{id}
    defaults: { _controller: AdminCategoryBundle:List:delete }
    requirements:
        id: \d+
        
