admin_news_homepage:
    path: /
    defaults: { _controller: AdminNewsBundle:News:index }
    
admin_news_detail:
    path: /detail/{id}
    defaults: { _controller: AdminNewsBundle:News:detail }
    requirements:
        id: \d+

admin_news_add:
    path: /add
    defaults: { _controller: AdminNewsBundle:News:add }
    
admin_news_edit:
    path: /edit/{id}
    defaults: { _controller: AdminNewsBundle:News:edit }
    requirements:
        id: \d+
    
admin_news_delete:
    path: /delete{id}
    defaults: { _controller: AdminNewsBundle:News:delete }
    requirements: 
        id: \d+