homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:homepage }
    
newspage:
    path: /newspage
    defaults: { _controller: AppBundle:Default:newspage }
    
carte:
    path: /carte
    defaults: { _controller: AppBundle:Default:carte }
    
infos-pratiques:
    path: /infos-pratiques
    defaults: { _controller: AppBundle:Default:infosPratiques }
    
partenaires:
    path: /partenaires
    defaults: { _controller: AppBundle:Default:partenaires }
    
trattoria:
    path: /trattoria
    defaults: { _controller: AppBundle:Default:trattoria }
 
nous-trouver:
    path: /nous-trouver
    defaults: { _controller: AppBundle:Default:nousTrouver }
    
nous-contacter:
    path: /nous-contacter
    defaults: { _controller: AppBundle:Default:nousContacter}
    
dejeuners:
    path: /dejeuners
    defaults: { _controller: AppBundle:Default:dejeuners }
    
desserts:
    path: /desserts
    defaults: { _controller: AppBundle:Default:desserts }

entrees:
   path: /entrees
   defaults: { _controller: AppBundle:Default:entrees }

hamburgers:
    path: /hamburgers
    defaults: { _controller: AppBundle:Default:hamburgers }

pates:
    path: /pates
    defaults: { _controller: AppBundle:Default:pates }

pizza:
    path: /pizza
    defaults: { _controller: AppBundle:Default:pizza }
 
poissons:
    path: /poissons
    defaults: { _controller: AppBundle:Default:poissons }
    
viandes:
    path: /viandes
    defaults: { _controller: AppBundle:Default:viandes }